### ISSUE TITLE
adding tv shows still on the air... what happens with new eipsodes?

### ISSUE THREAD

**Issue by psybertech** [vexorian/dizquetv#27] opened 2020-08-15 02:26 UTC
Sorry again for posting a question in the issues section....

So, when I add a tv series to a channel, the selection dialog pulls from Plex's current library scan.
But what happens if the show airs new episodes?
Will they be added when the next XMLTV update occurs? 
_I assume the channel playlist isn't actually generated as a one deal time for all the files and then stops... I assume its created based on the time slice you told the XMLTV data to be generated and only cares about what items can fill that time slice._

If it does keep adding new episodes, that is great!!!
But then, what about when a new season starts? Will they also be added or no, since the last time you added the show, only X seasons were listed, so season X+1 is completely unknown?

Just trying to figure out future channel maintenance on some channels I am making that have non-static content.

Thanks again!

cheers

j

**Comment by vexorian** [comment] 2020-08-15 02:29
Right now channels stay the way you left them. 

There's a feature planned for later in which you'd be able to configure the channel to update automatically as a playlist is updated. And if that playlist is a smart playlist, then when shows are added, they will be added to the channel too

Closing because it's a duplicate of  https://github.com/vexorian/dizquetv/issues/10

**Closed by vexorian** 2020-08-15 02:29 UTC
