### ISSUE TITLE
Using Balance Shows button Disables Pad Times button.

### ISSUE THREAD

**Issue by zerojay** [vexorian/dizquetv#310] opened 2021-05-13 11:51 UTC
Clicking on the Balance Shows button causes the Pad Times button to be permanently disabled on a channel, stopping the user from being able to pad their shows with flex time.

**Comment by vexorian** [comment] 2021-05-13 12:26
It's because balance shows made the channel's schedule too big

Even if the pad times button would be enabled. Clicking it would double the number of programs and it would be beyond the program count limit and you wouldn't be able to save it.

I recommend to use random slots instead of tweak weights nowadays. You have as much control of the weight but it will handle the padding and createa a schedule for a whole year and the channel will still be rather small.

**Comment by vexorian** [comment] 2021-05-16 11:43
Closing it because it's expected behavior

**Closed by vexorian** 2021-05-16 11:43 UTC
