### ISSUE TITLE
Stealth Channel at Night not showing program information in guide

### ISSUE THREAD

**Issue by kwbisch** [vexorian/dizquetv#95] opened 2020-09-07 00:51 UTC
The guide in both the dizque webgui and in Plex is not showing program information for my channel at night, which is a stealth channel.  To make this explanation easy, here's some definitions for the screenshots.

Main Channel - Cartoon Channel (aka "Cartoonito")
Stealth Channel - Cartoonito at Night

The main channel is configured to redirect to the stealth channel from 18:00 - 05:00.  The guide is showing only the name of the main channel instead of the individual programs.  I would expect that the guide show the name of the shows that will air.

For example, I would expect the guide to show "Mama's Family", followed by "Happy Days", followed by "The Andy Griffith Show" instead of just saying "Cartoonito".

![issue1-1](https://user-images.githubusercontent.com/42160517/92338967-4d7d7c80-f079-11ea-8b49-bafd91388410.png)
![issue1-2](https://user-images.githubusercontent.com/42160517/92338969-52423080-f079-11ea-8b7c-514192f10b4e.png)
![issue1-3](https://user-images.githubusercontent.com/42160517/92339113-1196e700-f07a-11ea-919e-7cc2f0295ede.png)
![issue1-4](https://user-images.githubusercontent.com/42160517/92339120-1cea1280-f07a-11ea-9182-ebda03ffb329.png)

**Comment by vexorian** [comment] 2020-09-07 01:35
Oh right, this is a bug with the stealth mechanism. Since the channel is stealth, the TV guide service doesn't preload the channel's data. Even though the channel's data may be necessary when there are redirects. Ironic because stealth feature was intended to complement channel at night. For now you'll have to make the channels not stealth until I fix it.

**Comment by vexorian** [comment] 2020-09-08 02:08
This is fixed in dev branch and the fix will be available in 0.0.68

**Closed by vexorian** 2020-09-08 02:08 UTC
Labels: bug
