### ISSUE TITLE
Buffering when trying to play Flex

### ISSUE THREAD

**Issue by scoobshub** [vexorian/dizquetv#185] opened 2020-11-03 20:40 UTC
This is a new thing that seems to happen just with channels that are setup with Time Slots. When a content ends, the Flex can't be loaded, Plex player just says "Buffering" and it stays like that (no error in console). You have to exit to the Plex Tv Guide and re-enter the same channel to see the Flex loading and playing without an issue; after that, when the flex ends, the next movie starts just fine.

This issue has been verified both on Plex for webos and Plex for Fire Tv.

Thanks

**Comment by vexorian** [comment] 2020-11-04 16:47
Are you sure this only happens when using time slots? If using flex in some other ways (like Add Breaks button), it doesn't happen?

**Comment by scoobshub** [comment] 2020-11-05 12:13
Hi @vexorian; thanks for your help. I can confirm (just tested) that the same file used as Flex in another channel via the "Add Breaks" button plays smoothly; in the channel with the time slots it hangs on buffering (black screen). If you need I can provide you the file used as flex (but it appears to me that all files are affected) or some logs or a recording when it happens ;)

**Comment by vexorian** [comment] 2020-11-05 12:35
This is really weird. For the video player part of dizquetv, it makes no difference if Time Slots or adding time was added. Are you using the same filler list in both cases? It could be that in one case the filler list is really large.

**Comment by scoobshub** [comment] 2020-11-05 13:33
Yes, i tried setting up the same filler list (only one video is added in it) and also adding the same clip as fallback. On a "normal" channel it plays perfectly, on time slotted channels it hangs (like you can see in [this](https://www.dropbox.com/s/3xxmv36mwpri2d9/rpreplay_final1604582275.mov?dl=0) video, where it's stuck buffering after the movie ends but closing and reopening the channel makes it work). Apparently, no error is displayed in the log.

**Comment by vexorian** [comment] 2020-11-05 13:36
New idea, use time slots , but with pick "maximum days to precalculate" equal to 1 day. Maybe the buffering is caused by the channel selector having to go through a huge list of programs.

**Comment by scoobshub** [comment] 2020-11-05 20:52
> New idea, use time slots , but with pick "maximum days to precalculate" equal to 1 day. Maybe the buffering is caused by the channel selector having to go through a huge list of programs.

Just tried that (total programs in the list: 29), but the issue is still happening

**Comment by scoobshub** [comment] 2020-11-25 21:00
@vexorian i think i found the culprit :) it' because of the "animated image"; to replicate:
- add animated icon to a channel 
- activate "animated image" in ffmpeg
- create time slots with flex (i can't say if this also happens for "regular" flex)
- tune in to the channel before the flex is loaded, it will "hang" forever giving you errors

Also note that the flex in this case is set to "disable channel watermark when playing filler". 
When turning off the animated logo, everything works perfectly ;)

**Comment by vexorian** [comment] 2020-11-25 21:45
That's really strange, but good to have it isolated.

**Comment by vexorian** [comment] 2021-01-10 00:21
Fixed in theory.

**Closed by vexorian** 2021-01-10 00:21 UTC
Labels: bug
